### ISSUE TITLE
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray

### ISSUE THREAD

**Issue by wxl123wxl** [xy-chen16/EpiAnno#1]
Hello
When I run EpiAnno using the code (python run_self_projection.py -d ../data/InSilico_count.hkl -c ../data/InSilico_cell_type.hkl -o outdir),(without -g gpu), only get some .npy files in outdir. And the last STDout is 

VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray

Do you know how to fix it.

**Comment by xy-chen16** [comment]
The output file is in .npy format. The model_xxx.npy file recorded the parameters of the model, and you can get the predicted labels and real labels of the test dataset in result_xxx.npy.
