### ISSUE TITLE
How to deal with large data?

### ISSUE THREAD

**Issue by lujiaying** [xy-chen16/EpiAnno#3]
Dear authors, 

I find your paper very interesting to follow. I appreciate that you release the code.
However, when I use it with my own data, it throws the following exceptions:

```
 File "run_crossdataset_projection.py", line 72, in <module>
    pmu,psigma,pz,pw,pnoise,px = EpiAnno.EpiAnno(10,data_train.shape[1],n_classes,sample_shape)
File "xxx/benchmark_EpiAnno/code/EpiAnno.py", line 29, in EpiAnno
    x = ed.Normal(loc = output, scale = noise, name = 'x')
...
lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_util.py", line 520, in make_tensor_proto
    "Cannot create a tensor proto whose content is larger than 2GB.")
ValueError: Cannot create a tensor proto whose content is larger than 2GB.
```

For `x = ed.Normal(loc = output, scale = noise, name = 'x')`,  input argument information is: `output shape=(8150, 72822), noise shape=(1,)`

I highly suspect it might be caused by my large input data,
```
total 21G
-rw-r--r-- 1 xxxx nts 126K Mar 21 22:37 ref-immunePBMC_PBMC_Rep1-cell_type.hkl
-rw-r--r-- 1 xxxx nts  13G Mar 21 22:44 ref-immunePBMC_PBMC_Rep1-data_count.hkl
-rw-r--r-- 1 xxxx nts 8.7G Mar 21 22:45 tgt-immunePBMC_ref_PBMC_Rep1_tgt_PBMC_Rep2-data_count.hkl
```

I was wondering by any chance you may know the solution or workaround for it?

Thanks!

**Comment by xy-chen16** [comment]
Mayby you can try to downsample the training set or set the ‘peak_rate’ parameter to 0.05 or greater.

**Comment by lujiaying** [comment]
Thanks @xy-chen16. I was able to work around the "2GB" limitation using downsampled data.
Unfortunately, I have encountered another exception:

```
Traceback (most recent call last):
  File "benchmark_EpiAnno/env_EpiAnno/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 2380, in get_attr
    c_api.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'qnoise/sample/random_gamma/RandomGamma' has no attr named '_XlaCompile'.

Traceback (most recent call last):
  File "run_crossdataset_projection.py", line 76, in <module>
    posterior_mu,posterior_sigma,posterior_qw = EpiAnno.train(qmu,qsigma,qw,elbo,sess,learning_rate,num_epochs,verbose)
  File "benchmark_EpiAnno/code/EpiAnno.py", line 109, in train
    train = optimizer.minimize(-elbo)
  File "benchmark_EpiAnno/env_EpiAnno/lib/python3.7/site-packages/tensorflow_core/python/training/optimizer.py", line 403, in minimize
    grad_loss=grad_loss)
...
...
  File "benchmark_EpiAnno/env_EpiAnno/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "benchmark_EpiAnno/env_EpiAnno/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 736, in __array__
    " array.".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (gradients/qnoise/sample/random_gamma/RandomGamma_grad/strided_slice:0) to a numpy array.
```

I did not encounter this issue when running the crossdataset demo you provided. 
From my knowledge, `ValueError: Operation 'qnoise/sample/random_gamma/RandomGamma' has no attr named '_XlaCompile'.` seems to be triggered by some packages not properly installed. But I did install cuda10.0 and packages in `requirements.txt`. And my python version is 3.7.11. Could you provide some insights?

**Comment by xy-chen16** [comment]
In my opinion, it seems that the Numpy package version is not compatible. I recommend using Numpy1.19.X, could you please have a try?

**Comment by lujiaying** [comment]
Thank you so much for the help. Yes, downgrade to Numpy1.19.x works!

**Comment by lujiaying** [comment]
I apologize to reopen this issue. 
After setting up big peak rate for some of my large-scale data, I found out that some cells might be discarded during prediction.
For instance, if I input a test matrix size = (45364, 426994). The predicted cell type contains only 45362 results.
By any chance would you know where I can avoid that? I speculate it might be caused by too big peak rate (0.10 in my case). 

I can provide my data if you want to replicate it.

**Comment by xy-chen16** [comment]
Such a large peak_rate may lead to generate some non-open-chromatin cells after preprocessing, the pipeline will filter out these cells before TF-IDF transformation.

**Comment by lujiaying** [comment]
Okay. Thank you for the information.
